---
# Chrony tasks file for sshockley.local

- name: 'chrony | Gather service facts'
  ansible.builtin.service_facts:

- name: 'chrony | Stop and disable systemd-timesyncd'
  become: true
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    state: stopped
    enabled: false
  when:
    - "'systemd-timesyncd.service' in ansible_facts.services"
    - ansible_facts.services['systemd-timesyncd.service'].status | default('unknown') not in ['unknown', 'not-found']

- name: 'chrony | Install chrony'
  become: true
  ansible.builtin.package:
    name: '{{ chrony_package }}'
    state: present

- name: 'chrony | Configure chronyd'
  become: true
  ansible.builtin.template:
    src: 'chrony.conf.j2'
    dest: '{{ chrony_config }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Restart chrony

- name: 'chrony | Enable and start chrony'
  become: true
  ansible.builtin.service:
    name: '{{ chrony_service }}'
    state: started
    enabled: true
