---
# Cockpit tasks file for sshockley.local

- name: 'cockpit | Create Cockpit directory'
  become: true
  ansible.builtin.file:
    path: '/etc/cockpit'
    state: directory
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

- name: 'cockpit | Install Cockpit disallowed-users'
  become: true
  ansible.builtin.template:
    src: 'cockpit-disallowed-users.j2'
    dest: '/etc/cockpit/disallowed-users'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
