---
# tasks file for sshockley.local

- name: Add OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_system }}.yml"
        - "main.yml"
      paths:
        - "vars"
  loop_control:
    loop_var: loop_vars
  tags:
    - configuration
    - packages

- name: Aliases
  ansible.builtin.include_tasks: aliases.yml

- name: Chrony
  ansible.builtin.include_tasks: chrony.yml

- name: Cockpit
  ansible.builtin.include_tasks: cockpit.yml
