---
# tasks file for sshockley.local

- name: 'Linux : Install aliases.sh'
  become: true
  ansible.builtin.template:
    src: 'aliases.sh.j2'
    dest: '/etc/profile.d/aliases.sh'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    seuser: system_u
    serole: object_r
    setype: bin_t
    selevel: s0

- name: 'Linux : Install Cockpit disallowed-users'
  become: true
  ansible.builtin.template:
    src: 'cockpit/disallowed-users.j2'
    dest: '/etc/cockpit/disallowed-users'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
